name: Publish
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  publish:
    name: Publish
    uses: emacscollective/workflows/.github/workflows/jekyll.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
